### ISSUE TITLE
Eclipse IDE keeps crashing

### ISSUE THREAD

**Issue by AussieScorpio** [eclipse-packaging/packages#143]
I'm running Eclipse IDE 2024-03. This is a new install on a new machine running Ubuntu 22.04.
I started having issues with Eclipse crashing intermittently when pasting into an editor window. There seemed to be no consistency as to when this occurs. Recently other actions are causing Eclipse to crash. Simply scrolling an editor window seems to be enough to make it happen. I've attempted to begin troubleshooting by reviewing installed software, but attempting to review installed software also causes Eclipse to crash.
The crash is immediate. There is no saving of workspace. There are no dialogues or warnings. Nothing is written to the workspace log file.
Eclipse has now become unusable.

**Comment by merks** [comment]
Does your issue sound like any of these?

https://github.com/eclipse-platform/eclipse.platform.swt/issues?q=is%3Aissue+is%3Aopen+crash

Your report is likely to fester here because the packing project just repackages things provided by other projects so if Eclipse is crashing, it's most likely ans SWT issue that needs to be fixed there and reported there.

Note  how this report contains a lot of details that are missing from your report:

https://github.com/eclipse-platform/eclipse.platform.swt/issues/1169

If you file a report against SWT, please link it to this report.  Or if one of the various workarounds in the other reports help, please let us know specifically which one helped you.

**Comment by AussieScorpio** [comment]
> Does your issue sound like any of these?
> 
> https://github.com/eclipse-platform/eclipse.platform.swt/issues?q=is%3Aissue+is%3Aopen+crash
> 
> Your report is likely to fester here because the packing project just repackages things provided by other projects so if Eclipse is crashing, it's most likely ans SWT issue that needs to be fixed there and reported there.
> 
> Note how this report contains a lot of details that are missing from your report:
> 
> [eclipse-platform/eclipse.platform.swt#1169](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1169)
> 
> If you file a report against SWT, please link it to this report. Or if one of the various workarounds in the other reports help, please let us know specifically which one helped you.

Thanks for pointing me in the right direction.

I've tried the following in terminal;
export GDK_BACKEND=x11
./eclipse

and this seems to have resolved all issues. I can paste into editor windows and scroll without issues. Whilst not ideal, and Eclipse should be able to run under Ubuntu's default; Wayland, this workaround is not too onerous.

It might be helpful to have Eclipse issue a warning if an incompatible rendering system is being used. Having every user of major distros like Fedora, Debian, Ubuntu have to go through the pain of troubleshooting this known issue costs a lot of man-hours and will ultimately hurt Eclipse's reputation and marketshare.

**Comment by merks** [comment]
Thank you for sharing your solution.   It seems good to suggest that perhaps SWT or some other UI component could detect configurations that are known not to work and warn the user, suggesting a workaround.  I'll ask if such a thing is possible...
