### ISSUE TITLE
eclipse-inst-jre-win64.exe

### ISSUE THREAD

**Issue by itclientmanagement** [eclipse-packaging/packages#230]
Hi,
we're trying to install the eclipse software (eclipse-inst-jre-win64.exe) but once is installed and we run the installer we got this issue (see file attached). Would it be possible to help us in order to fix it, please?
[logs eclipse.txt](https://github.com/user-attachments/files/17644218/logs.eclipse.txt)

thanks in advance

kind regards

**Comment by merks** [comment]
Try using this installer:

https://www.eclipse.org/downloads/download.php?file=/oomph/products/eclipse-inst-jre-win64.exe

It uses this in the eclipse-inst.ini
```
-Djavax.net.ssl.trustStoreType=Windows-ROOT
-Djavax.net.ssl.trustStore=NONE
```
You can add that to the eclipse.ini of the installation too because it will have the same problem.

These issue should be better for the 2024-12 release which you can try from here:

https://www.eclipse.org/downloads/packages/release/2024-12/m2

I.e., the installer includes those options and the installations will also include those options...

**Comment by itclientmanagement** [comment]
> Try using this installer:
> 
> https://www.eclipse.org/downloads/download.php?file=/oomph/products/eclipse-inst-jre-win64.exe
> 
> It uses this in the eclipse-inst.ini
> 
> ```
> -Djavax.net.ssl.trustStoreType=Windows-ROOT
> -Djavax.net.ssl.trustStore=NONE
> ```
> 
> You can add that to the eclipse.ini of the installation too because it will have the same problem.
> 
> These issue should be better for the 2024-12 release which you can try from here:
> 
> https://www.eclipse.org/downloads/packages/release/2024-12/m2
> 
> I.e., the installer includes those options and the installations will also include those options...


https://www.eclipse.org/downloads/download.php?file=/oomph/products/eclipse-inst-jre-win64.exe
Do you have the manual installation? The all steps? Once i run the eclipse-inst-jre-win64.exe i got a different eclipse options to install it.

-Djavax.net.ssl.trustStoreType=Windows-ROOT
> -Djavax.net.ssl.trustStore=NONE
where should i add these two lines?

**Comment by merks** [comment]
If in doubt, use the installer from this page and all should work without manual steps doing exactly the same as what you already tried:

- https://www.eclipse.org/downloads/packages/release/2024-12/m2
- https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2024-12/M3/eclipse-inst-jre-win64.exe

**Comment by itclientmanagement** [comment]
Hi Merks,
I've just downloaded the file but i'd like to share the installation steps to see if we're doing correctly:
1. Run [eclipse-inst-jre-win64.exe](https://www.eclipse.org/downloads/download.php?file=/oomph/products/eclipse-inst-jre-win64.exe)
2-. Once it has finished the installation i got this
<img width="320" alt="image" src="https://github.com/user-attachments/assets/505033b1-b718-491e-88bc-d16594792579">
3-. I selected the Eclipse Modeling Tools, for example:
<img width="587" alt="image" src="https://github.com/user-attachments/assets/463d37f8-50a7-4b7e-830d-df6fef9ea67e">
4-. Before it finish the installation it appears en error message
<img width="587" alt="image" src="https://github.com/user-attachments/assets/ba597d37-2f17-4357-93de-85a7ac02ce34">

i attached the logs
[logs eclipse 2.txt](https://github.com/user-attachments/files/17645500/logs.eclipse.2.txt)

i'm not sure if i'm missing something in the installation. I'm using windows 11 enterprise 23h2

**Comment by merks** [comment]
You say you are downloading this:

https://www.eclipse.org/downloads/download.php?file=/oomph/products/eclipse-inst-jre-win64.exe

But I I think perhaps you did not actually run what you downloaded, probably because it has the same name so you ended with eclipse-inst-jre-win64(xxx).exe and didn't actually run that...

Anyway, I won't be able to help further for today.
