### ISSUE TITLE
Ant 1.10.14 does not "get along" with EPP

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-packaging/packages#66]
Since Eclipse Platform update SimRel to a version containing Ant 1.10.14 the EPP has failed to build:

```java
19:33:57 Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.eclipse.orbit:ant:jar:1.10.14 in eclipse.maven.central.mirror (https://repo.eclipse.org/content/repositories/maven_central/)
19:33:57     at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed (ArtifactTransportListener.java:48)
19:33:57     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:369)
19:33:57     at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
19:33:57     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1136)
19:33:57     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:635)
19:33:57     at java.lang.Thread.run (Thread.java:833)
```

**Comment by jonahgraham** [comment]
I suspect this has something to do with Ant's unusual packaging and Tycho's going back to Maven to collect maven artifacts (see https://github.com/eclipse-tycho/tycho/discussions/2732) - but perhaps it is just a coincidence. 

This is a blocker of an issue that prevents us from building EPP for 2023-12 M1.

FYI: @merks

**Comment by jonahgraham** [comment]
I raised https://github.com/eclipse-tycho/tycho/issues/2881 because I think this is a Tycho bug.

**Comment by merks** [comment]
Yes, I encountered this with EMF's build yesterday and was pulling my hair out about the cause...

I can probably fix/change this in Orbit if I promoted to a Maven coordinate that exists on Maven:

https://github.com/eclipse-orbit/orbit-simrel/blob/f6ea491f4ada5d6d6750d8118bf40d9802993376/maven-bnd/tp/MavenBND.target#L1193-L1210

I wasn't sure if many it's caused by the way the I-Build is published to snapshots...
